#ifndef ZOD_EFFECT_HPP
#define ZOD_EFFECT_HPP
// =========================================================
// ******* includes all zod engine effects *****************
// =========================================================
#include "qzod_effect_old.h"
// =========================================================
// *********************************************************
// =========================================================
#include "ebridgeturrent.h"
#include "ebullet.h"
#include "ecannondeath.h"
#include "ecraneconco.h"
#include "edeath.h"
#include "edeathsparks.h"
#include "eflame.h"
#include "elaser.h"
#include "elightinitfire.h"
#include "elightrocket.h"
#include "emapobjectturrent.h"
#include "emissilecrockets.h"
#include "emomissilerockets.h"
#include "epyrofire.h"
#include "erobotdeath.h"
#include "erobotturrent.h"
#include "erockparticle.h"
#include "erockturrent.h"
#include "esideexplosion.h"
#include "estandard.h"
#include "etankdirt.h"
#include "etankoil.h"
#include "etanksmoke.h"
#include "etankspark.h"
#include "etoughmushroom.h"
#include "etoughrocket.h"
#include "etoughsmoke.h"
#include "etrack.h"
#include "eturrentmissile.h"
#include "eunitparticle.h"
// =========================================================
// *********************************************************
// =========================================================
#endif // ZOD_EFFECT_HPP
